// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEaPosX7v1fDJSEym-PGH9bZTiI19BnDk',
    appId: '1:413930215700:web:23185eeccfdc961cd94a01',
    messagingSenderId: '413930215700',
    projectId: 'meetup-fde43',
    authDomain: 'meetup-fde43.firebaseapp.com',
    storageBucket: 'meetup-fde43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJOvTiSbGu7jFLgmWjecHJDAPMs42CPiE',
    appId: '1:413930215700:android:270168f035e7fc7ad94a01',
    messagingSenderId: '413930215700',
    projectId: 'meetup-fde43',
    storageBucket: 'meetup-fde43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOlhkzx7N7FWX9xKgwq1q-kLGG667dR0',
    appId: '1:413930215700:ios:9a05e3c231a39f07d94a01',
    messagingSenderId: '413930215700',
    projectId: 'meetup-fde43',
    storageBucket: 'meetup-fde43.appspot.com',
    iosClientId: '413930215700-ijp1s6mko9b89q1dibh8sle5bqhmhujr.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkOlhkzx7N7FWX9xKgwq1q-kLGG667dR0',
    appId: '1:413930215700:ios:9a05e3c231a39f07d94a01',
    messagingSenderId: '413930215700',
    projectId: 'meetup-fde43',
    storageBucket: 'meetup-fde43.appspot.com',
    iosClientId: '413930215700-ijp1s6mko9b89q1dibh8sle5bqhmhujr.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetup',
  );
}
